# Site settings
title: Computational Methods in Atmospheric and Oceanic Sciences
short_title: Computational Methods in AOS
email: aos573@lists
description: "AOS573"
baseurl: ""
url: "https://aos573.github.io"

# Build settings
markdown: kramdown
permalink: pretty
syntax_highligher: ultraviolet

syntax_highlighter_opts:
  line_numbers: ''

collections:
  lectures:
    output: true
    permalink: /lectures/:path.html
  assignments:
    output: true
    permalink: /assignments/:path.html
